### ISSUE TITLE
pip package is missing dependencies

### ISSUE THREAD

**Issue by melonmouse** [texturedesign/texturize#37]
The dependencies listed in pip are: `creativeai`, `docopt`, `progressbar2`, `schema`

It seems the missing dependencies are: `ipython`, `ipywidgets`, `Pillow`, `protobuf`, `torch` and `torchvision`.

**Comment by alexjc** [comment]
The dependencies are installed with conda via the YAML file. See the README.txt for details.

The pip installation will not install any `torch` version for you (it's intentional), as that's expected to be installed externally beforehand.  I could include an `[all]` dependencies that you can forcefully install?

(Closing this for now, but if anyone has strong preferences please indicate them.)

**Comment by melonmouse** [comment]
Thanks for your reply!

Adding a minimum required version of `torch` in `pyproject.toml` would be best of both worlds right?

If you already have a compatible version of `torch` (externally):
:arrow_right: no new version is installed :heavy_check_mark: 
If you **don't** have a compatible version of `torch` (externally):
:arrow_right: user is asked if they want to update `torch` or cancel the installation :heavy_check_mark:

Maybe for `torch` the impact is relatively small, because a lot of people have it already, but there are several missing dependencies: `ipython`, `ipywidgets`, `Pillow`, `protobuf` and `torchvision`. Lots of people will not have one of those.
